spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
#        globally_quoted_identifiers: true
    datasource:
      schema: classpath*:db/h2/schema.sql
      data: classpath*:db/h2/import.sql
  data:
    web:
      pageable:
        one-indexed-parameters: true

mail:
  address:
    admin: admin@gmail.com

jwt:
  secret-key: HelloBaskinRobbins31YouAreGood!!
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
