spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 091397
    url: jdbc:mysql://localhost:3306/stackoverflow?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  data:
    web:
      pageable:
        one-indexed-parameters: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: HelloBaskinRobbins31YouAreGood!!
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
