# 더미데이터 들어가는 버전

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
mail:
  address:
    admin: admin@gmail.com

jwt:
  secret-key: HelloBaskinRobbins31YouAreGood!!
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
